In [24]:
import pandas as pd
import os
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [25]:
df = pd.read_csv('Encrypted_Data.csv')

def symmetric_encrypt(value):
    hashed_value = hash(value)
    encrypted_value = hashed_value % 1000000 
    return encrypted_value

df = df.applymap(symmetric_encrypt)

df.to_csv('Symmetric_Encrypted_Data.csv', index=False)

def symmetric_decrypt(encrypted_value):
    return encrypted_value

with open('Decryption_Key.pkl', 'wb') as key_file:
    pickle.dump(symmetric_decrypt, key_file)

C:\Users\USER\AppData\Local\Temp\ipykernel_18352\3193653495.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(symmetric_encrypt)

In [26]:
X = df.drop(['HeartDisease'], axis='columns')
X

,Age,Sex,ChestPainType,RestingBloodPressure,Cholesterol,FastingBloodSugar,RestingECG,MaximumHeartRate,ExerciseAngina,Oldpeak,ST_Slope
0,631476,789171,532808,350156,523738,141267,101633,874714,171055,366160,695512
1,143491,44994,364362,490297,890230,141267,101633,975780,171055,137703,212548
2,470648,789171,532808,61823,770307,141267,891717,677230,171055,366160,695512
3,375088,44994,231647,364921,746503,141267,101633,715291,437934,844081,212548
4,767422,789171,364362,111865,447052,141267,101633,114433,171055,366160,695512
...,...,...,...,...,...,...,...,...,...,...,...
2855,157967,789171,231647,732157,70886,141267,891717,119092,437934,366160,212548
2856,319045,789171,231647,911241,108355,141267,818966,125134,171055,366160,212548
2857,767422,44994,231647,824502,355699,523217,891717,606341,171055,366160,212548
2858,358055,789171,231647,327250,286228,523217,891717,548640,171055,366160,212548
2859,157967,789171,532808,193220,583869,141267,838526,103270,437934,366160,212548

In [27]:
Y = df[['HeartDisease']]
Y

      HeartDisease
0           793135
1           530719
2           793135
3           530719
4           793135
...            ...
2855        530719
2856        530719
2857        530719
2858        530719
2859        530719

[2860 rows x 1 columns]

In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.9) #, random_state=10)

In [29]:
len(X_train)

2574

In [30]:
len(X_test)

286

In [31]:
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train, Y_train)
model.score(X_train, Y_train)

0.3192564271030085

In [32]:
from sklearn import linear_model
model = linear_model.LogisticRegression()
model.fit(X_train, Y_train)
model.score(X_train, Y_train)

c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7455322455322455

In [33]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train, Y_train)
model.score(X_test,Y_test)

0.8006993006993007

In [34]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, Y_train)
model.score(X_test, Y_test)

c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.790986790986791